name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: build and push 
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: create Docker network
        run: docker network create my-network

      - name: build MySQL Docker image
        run: |
          cd springboot_backend/data_migration
          docker build -t my-mysql-image .

      - name: run MySQL container
        run: |
          docker run --name my-mysql-container --network my-network -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=ace -p 3307:3306 -d my-mysql-image

      - name: wait for db
        run: |
          until docker exec my-mysql-container mysqladmin ping --silent; do
            echo 'waiting for mysql to be connectable...'
            sleep 2
          done

      - name: run unit tests
        run: mvn -B test --file springboot_backend/pom.xml

      - name: build the app
        run: |
           cd springboot_backend
           mvn clean
           mvn -B package --file pom.xml

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build and push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./springboot_backend  # Set the context to the directory containing the Dockerfile
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ace_backend:latest
